name: Packer Build

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build-ami:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Packer Build
    env:
      DB_HOST: ${{secrets.DB_HOST }}
      DB_PORT: ${{secrets.DB_PORT}}
      PORT: ${{secrets.PORT}}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DIALECT: ${{secrets.DIALECT}}
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_REGION: ${{secrets.AWS_REGION}}
      INSTANCE_TYPE: ${{secrets.INSTANCE_TYPE}}
      SSH_USERNAME: ${{secrets.SSH_USERNAME}}
      SUBNET_ID: ${{secrets.SUBNET_ID}}
      VPC_ID: ${{secrets.VPC_ID}}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: create .env
        run: |
          echo "${{ secrets.ENV_VARS }}" > .env
      
      - name: Install Packer
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          curl -LO https://releases.hashicorp.com/packer/1.11.2/packer_1.11.2_linux_amd64.zip
          unzip packer_1.11.2_linux_amd64.zip
          sudo mv packer /usr/local/bin/
          packer --version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{secrets.AWS_REGION}}

      - name: create variables.pkrvars.hcl
        run: |
          echo "${{ secrets.PKR_VARS }}" > variables.pkrvars.hcl 
          
      - name: Create webapp.zip from existing directory
        run: |
          zip -r webapp.zip .
        shell: bash
      
      - name: packer init
        run: packer init .
      
      - name: packer fmt
        run: packer fmt -check -recursive

      
      
      - name: packer validate
        run: packer validate -var-file=variables.pkrvars.hcl

      - name: Build AMI
        run: |
          packer init .
          packer build aws.pkr.hcl